/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the FoldersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FoldersResponse{}

// FoldersResponse struct for FoldersResponse
type FoldersResponse struct {
	Status *Status `json:"status,omitempty"`
	Data []Folder `json:"data,omitempty"`
}

// NewFoldersResponse instantiates a new FoldersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFoldersResponse() *FoldersResponse {
	this := FoldersResponse{}
	return &this
}

// NewFoldersResponseWithDefaults instantiates a new FoldersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFoldersResponseWithDefaults() *FoldersResponse {
	this := FoldersResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FoldersResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FoldersResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FoldersResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *FoldersResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FoldersResponse) GetData() []Folder {
	if o == nil || IsNil(o.Data) {
		var ret []Folder
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FoldersResponse) GetDataOk() ([]Folder, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FoldersResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Folder and assigns it to the Data field.
func (o *FoldersResponse) SetData(v []Folder) {
	o.Data = v
}

func (o FoldersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FoldersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFoldersResponse struct {
	value *FoldersResponse
	isSet bool
}

func (v NullableFoldersResponse) Get() *FoldersResponse {
	return v.value
}

func (v *NullableFoldersResponse) Set(val *FoldersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFoldersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFoldersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFoldersResponse(val *FoldersResponse) *NullableFoldersResponse {
	return &NullableFoldersResponse{value: val, isSet: true}
}

func (v NullableFoldersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFoldersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


