/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the EmailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailsResponse{}

// EmailsResponse struct for EmailsResponse
type EmailsResponse struct {
	Status *Status `json:"status,omitempty"`
	Data []Email `json:"data,omitempty"`
}

// NewEmailsResponse instantiates a new EmailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailsResponse() *EmailsResponse {
	this := EmailsResponse{}
	return &this
}

// NewEmailsResponseWithDefaults instantiates a new EmailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailsResponseWithDefaults() *EmailsResponse {
	this := EmailsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailsResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailsResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *EmailsResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailsResponse) GetData() []Email {
	if o == nil || IsNil(o.Data) {
		var ret []Email
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailsResponse) GetDataOk() ([]Email, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Email and assigns it to the Data field.
func (o *EmailsResponse) SetData(v []Email) {
	o.Data = v
}

func (o EmailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEmailsResponse struct {
	value *EmailsResponse
	isSet bool
}

func (v NullableEmailsResponse) Get() *EmailsResponse {
	return v.value
}

func (v *NullableEmailsResponse) Set(val *EmailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailsResponse(val *EmailsResponse) *NullableEmailsResponse {
	return &NullableEmailsResponse{value: val, isSet: true}
}

func (v NullableEmailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


