/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the Attachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Attachment{}

// Attachment struct for Attachment
type Attachment struct {
	// store name.
	StoreName *string `json:"storeName,omitempty"`
	// Name of the attachment file.
	AttachmentName *string `json:"attachmentName,omitempty"`
	// Attachment Path
	AttachmentPath *string `json:"attachmentPath,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewAttachment instantiates a new Attachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachment() *Attachment {
	this := Attachment{}
	return &this
}

// NewAttachmentWithDefaults instantiates a new Attachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentWithDefaults() *Attachment {
	this := Attachment{}
	return &this
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *Attachment) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *Attachment) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *Attachment) SetStoreName(v string) {
	o.StoreName = &v
}

// GetAttachmentName returns the AttachmentName field value if set, zero value otherwise.
func (o *Attachment) GetAttachmentName() string {
	if o == nil || IsNil(o.AttachmentName) {
		var ret string
		return ret
	}
	return *o.AttachmentName
}

// GetAttachmentNameOk returns a tuple with the AttachmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetAttachmentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentName) {
		return nil, false
	}
	return o.AttachmentName, true
}

// HasAttachmentName returns a boolean if a field has been set.
func (o *Attachment) HasAttachmentName() bool {
	if o != nil && !IsNil(o.AttachmentName) {
		return true
	}

	return false
}

// SetAttachmentName gets a reference to the given string and assigns it to the AttachmentName field.
func (o *Attachment) SetAttachmentName(v string) {
	o.AttachmentName = &v
}

// GetAttachmentPath returns the AttachmentPath field value if set, zero value otherwise.
func (o *Attachment) GetAttachmentPath() string {
	if o == nil || IsNil(o.AttachmentPath) {
		var ret string
		return ret
	}
	return *o.AttachmentPath
}

// GetAttachmentPathOk returns a tuple with the AttachmentPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetAttachmentPathOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentPath) {
		return nil, false
	}
	return o.AttachmentPath, true
}

// HasAttachmentPath returns a boolean if a field has been set.
func (o *Attachment) HasAttachmentPath() bool {
	if o != nil && !IsNil(o.AttachmentPath) {
		return true
	}

	return false
}

// SetAttachmentPath gets a reference to the given string and assigns it to the AttachmentPath field.
func (o *Attachment) SetAttachmentPath(v string) {
	o.AttachmentPath = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Attachment) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Attachment) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Attachment) SetUrl(v string) {
	o.Url = &v
}

func (o Attachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Attachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoreName) {
		toSerialize["storeName"] = o.StoreName
	}
	if !IsNil(o.AttachmentName) {
		toSerialize["attachmentName"] = o.AttachmentName
	}
	if !IsNil(o.AttachmentPath) {
		toSerialize["attachmentPath"] = o.AttachmentPath
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAttachment struct {
	value *Attachment
	isSet bool
}

func (v NullableAttachment) Get() *Attachment {
	return v.value
}

func (v *NullableAttachment) Set(val *Attachment) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachment(val *Attachment) *NullableAttachment {
	return &NullableAttachment{value: val, isSet: true}
}

func (v NullableAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


