/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the AttachmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachmentsResponse{}

// AttachmentsResponse struct for AttachmentsResponse
type AttachmentsResponse struct {
	Status *Status `json:"status,omitempty"`
	Data []Attachment `json:"data,omitempty"`
}

// NewAttachmentsResponse instantiates a new AttachmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentsResponse() *AttachmentsResponse {
	this := AttachmentsResponse{}
	return &this
}

// NewAttachmentsResponseWithDefaults instantiates a new AttachmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentsResponseWithDefaults() *AttachmentsResponse {
	this := AttachmentsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AttachmentsResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentsResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AttachmentsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *AttachmentsResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AttachmentsResponse) GetData() []Attachment {
	if o == nil || IsNil(o.Data) {
		var ret []Attachment
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentsResponse) GetDataOk() ([]Attachment, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AttachmentsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Attachment and assigns it to the Data field.
func (o *AttachmentsResponse) SetData(v []Attachment) {
	o.Data = v
}

func (o AttachmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAttachmentsResponse struct {
	value *AttachmentsResponse
	isSet bool
}

func (v NullableAttachmentsResponse) Get() *AttachmentsResponse {
	return v.value
}

func (v *NullableAttachmentsResponse) Set(val *AttachmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentsResponse(val *AttachmentsResponse) *NullableAttachmentsResponse {
	return &NullableAttachmentsResponse{value: val, isSet: true}
}

func (v NullableAttachmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


