/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the EmailContentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailContentResponse{}

// EmailContentResponse struct for EmailContentResponse
type EmailContentResponse struct {
	Status *Status `json:"status,omitempty"`
	Data *EmailContentResponseData `json:"data,omitempty"`
}

// NewEmailContentResponse instantiates a new EmailContentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailContentResponse() *EmailContentResponse {
	this := EmailContentResponse{}
	return &this
}

// NewEmailContentResponseWithDefaults instantiates a new EmailContentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailContentResponseWithDefaults() *EmailContentResponse {
	this := EmailContentResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailContentResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailContentResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailContentResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *EmailContentResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailContentResponse) GetData() EmailContentResponseData {
	if o == nil || IsNil(o.Data) {
		var ret EmailContentResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailContentResponse) GetDataOk() (*EmailContentResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailContentResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EmailContentResponseData and assigns it to the Data field.
func (o *EmailContentResponse) SetData(v EmailContentResponseData) {
	o.Data = &v
}

func (o EmailContentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailContentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEmailContentResponse struct {
	value *EmailContentResponse
	isSet bool
}

func (v NullableEmailContentResponse) Get() *EmailContentResponse {
	return v.value
}

func (v *NullableEmailContentResponse) Set(val *EmailContentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailContentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailContentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailContentResponse(val *EmailContentResponse) *NullableEmailContentResponse {
	return &NullableEmailContentResponse{value: val, isSet: true}
}

func (v NullableEmailContentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailContentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


