/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the EmailHeaderRawResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailHeaderRawResponse{}

// EmailHeaderRawResponse struct for EmailHeaderRawResponse
type EmailHeaderRawResponse struct {
	Status *Status `json:"status,omitempty"`
	Data *EmailHeaderRawResponseData `json:"data,omitempty"`
}

// NewEmailHeaderRawResponse instantiates a new EmailHeaderRawResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailHeaderRawResponse() *EmailHeaderRawResponse {
	this := EmailHeaderRawResponse{}
	return &this
}

// NewEmailHeaderRawResponseWithDefaults instantiates a new EmailHeaderRawResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailHeaderRawResponseWithDefaults() *EmailHeaderRawResponse {
	this := EmailHeaderRawResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailHeaderRawResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailHeaderRawResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailHeaderRawResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *EmailHeaderRawResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailHeaderRawResponse) GetData() EmailHeaderRawResponseData {
	if o == nil || IsNil(o.Data) {
		var ret EmailHeaderRawResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailHeaderRawResponse) GetDataOk() (*EmailHeaderRawResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailHeaderRawResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EmailHeaderRawResponseData and assigns it to the Data field.
func (o *EmailHeaderRawResponse) SetData(v EmailHeaderRawResponseData) {
	o.Data = &v
}

func (o EmailHeaderRawResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailHeaderRawResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEmailHeaderRawResponse struct {
	value *EmailHeaderRawResponse
	isSet bool
}

func (v NullableEmailHeaderRawResponse) Get() *EmailHeaderRawResponse {
	return v.value
}

func (v *NullableEmailHeaderRawResponse) Set(val *EmailHeaderRawResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailHeaderRawResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailHeaderRawResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailHeaderRawResponse(val *EmailHeaderRawResponse) *NullableEmailHeaderRawResponse {
	return &NullableEmailHeaderRawResponse{value: val, isSet: true}
}

func (v NullableEmailHeaderRawResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailHeaderRawResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


