/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
	"fmt"
)


// GetMessageHeader200Response struct for GetMessageHeader200Response
type GetMessageHeader200Response struct {
	EmailHeaderRawResponse *EmailHeaderRawResponse
	EmailHeaderResponse *EmailHeaderResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetMessageHeader200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into EmailHeaderRawResponse
	err = json.Unmarshal(data, &dst.EmailHeaderRawResponse);
	if err == nil {
		jsonEmailHeaderRawResponse, _ := json.Marshal(dst.EmailHeaderRawResponse)
		if string(jsonEmailHeaderRawResponse) == "{}" { // empty struct
			dst.EmailHeaderRawResponse = nil
		} else {
			return nil // data stored in dst.EmailHeaderRawResponse, return on the first match
		}
	} else {
		dst.EmailHeaderRawResponse = nil
	}

	// try to unmarshal JSON data into EmailHeaderResponse
	err = json.Unmarshal(data, &dst.EmailHeaderResponse);
	if err == nil {
		jsonEmailHeaderResponse, _ := json.Marshal(dst.EmailHeaderResponse)
		if string(jsonEmailHeaderResponse) == "{}" { // empty struct
			dst.EmailHeaderResponse = nil
		} else {
			return nil // data stored in dst.EmailHeaderResponse, return on the first match
		}
	} else {
		dst.EmailHeaderResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetMessageHeader200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetMessageHeader200Response) MarshalJSON() ([]byte, error) {
	if src.EmailHeaderRawResponse != nil {
		return json.Marshal(&src.EmailHeaderRawResponse)
	}

	if src.EmailHeaderResponse != nil {
		return json.Marshal(&src.EmailHeaderResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetMessageHeader200Response struct {
	value *GetMessageHeader200Response
	isSet bool
}

func (v NullableGetMessageHeader200Response) Get() *GetMessageHeader200Response {
	return v.value
}

func (v *NullableGetMessageHeader200Response) Set(val *GetMessageHeader200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMessageHeader200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMessageHeader200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMessageHeader200Response(val *GetMessageHeader200Response) *NullableGetMessageHeader200Response {
	return &NullableGetMessageHeader200Response{value: val, isSet: true}
}

func (v NullableGetMessageHeader200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMessageHeader200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


