/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the NoDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoDataResponse{}

// NoDataResponse struct for NoDataResponse
type NoDataResponse struct {
	Status *Status `json:"status,omitempty"`
}

// NewNoDataResponse instantiates a new NoDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoDataResponse() *NoDataResponse {
	this := NoDataResponse{}
	return &this
}

// NewNoDataResponseWithDefaults instantiates a new NoDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoDataResponseWithDefaults() *NoDataResponse {
	this := NoDataResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NoDataResponse) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoDataResponse) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NoDataResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *NoDataResponse) SetStatus(v Status) {
	o.Status = &v
}

func (o NoDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableNoDataResponse struct {
	value *NoDataResponse
	isSet bool
}

func (v NullableNoDataResponse) Get() *NoDataResponse {
	return v.value
}

func (v *NullableNoDataResponse) Set(val *NoDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNoDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNoDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoDataResponse(val *NoDataResponse) *NullableNoDataResponse {
	return &NullableNoDataResponse{value: val, isSet: true}
}

func (v NullableNoDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


