/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the EmailHeaderDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailHeaderDetails{}

// EmailHeaderDetails struct for EmailHeaderDetails
type EmailHeaderDetails struct {
	HeaderContent *EmailHeaderDetailsHeaderContent `json:"headerContent,omitempty"`
	MessageId *int64 `json:"messageId,omitempty"`
}

// NewEmailHeaderDetails instantiates a new EmailHeaderDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailHeaderDetails() *EmailHeaderDetails {
	this := EmailHeaderDetails{}
	return &this
}

// NewEmailHeaderDetailsWithDefaults instantiates a new EmailHeaderDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailHeaderDetailsWithDefaults() *EmailHeaderDetails {
	this := EmailHeaderDetails{}
	return &this
}

// GetHeaderContent returns the HeaderContent field value if set, zero value otherwise.
func (o *EmailHeaderDetails) GetHeaderContent() EmailHeaderDetailsHeaderContent {
	if o == nil || IsNil(o.HeaderContent) {
		var ret EmailHeaderDetailsHeaderContent
		return ret
	}
	return *o.HeaderContent
}

// GetHeaderContentOk returns a tuple with the HeaderContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailHeaderDetails) GetHeaderContentOk() (*EmailHeaderDetailsHeaderContent, bool) {
	if o == nil || IsNil(o.HeaderContent) {
		return nil, false
	}
	return o.HeaderContent, true
}

// HasHeaderContent returns a boolean if a field has been set.
func (o *EmailHeaderDetails) HasHeaderContent() bool {
	if o != nil && !IsNil(o.HeaderContent) {
		return true
	}

	return false
}

// SetHeaderContent gets a reference to the given EmailHeaderDetailsHeaderContent and assigns it to the HeaderContent field.
func (o *EmailHeaderDetails) SetHeaderContent(v EmailHeaderDetailsHeaderContent) {
	o.HeaderContent = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *EmailHeaderDetails) GetMessageId() int64 {
	if o == nil || IsNil(o.MessageId) {
		var ret int64
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailHeaderDetails) GetMessageIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *EmailHeaderDetails) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given int64 and assigns it to the MessageId field.
func (o *EmailHeaderDetails) SetMessageId(v int64) {
	o.MessageId = &v
}

func (o EmailHeaderDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailHeaderDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HeaderContent) {
		toSerialize["headerContent"] = o.HeaderContent
	}
	if !IsNil(o.MessageId) {
		toSerialize["messageId"] = o.MessageId
	}
	return toSerialize, nil
}

type NullableEmailHeaderDetails struct {
	value *EmailHeaderDetails
	isSet bool
}

func (v NullableEmailHeaderDetails) Get() *EmailHeaderDetails {
	return v.value
}

func (v *NullableEmailHeaderDetails) Set(val *EmailHeaderDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailHeaderDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailHeaderDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailHeaderDetails(val *EmailHeaderDetails) *NullableEmailHeaderDetails {
	return &NullableEmailHeaderDetails{value: val, isSet: true}
}

func (v NullableEmailHeaderDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailHeaderDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


