/*
Zoho Mail API

This is a Zoho Mail API OpenAPI 3.0 specification

API version: 1.0.0
Contact: vigneshwaran4817@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zmail

import (
	"encoding/json"
)

// checks if the EmailAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAttachment{}

// EmailAttachment struct for EmailAttachment
type EmailAttachment struct {
	// Size of the attachment in bytes.
	AttachmentSize *int32 `json:"attachmentSize,omitempty"`
	// Name of the attachment file.
	AttachmentName *string `json:"attachmentName,omitempty"`
	// Unique identifier for the attachment.
	AttachmentId *string `json:"attachmentId,omitempty"`
}

// NewEmailAttachment instantiates a new EmailAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAttachment() *EmailAttachment {
	this := EmailAttachment{}
	return &this
}

// NewEmailAttachmentWithDefaults instantiates a new EmailAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailAttachmentWithDefaults() *EmailAttachment {
	this := EmailAttachment{}
	return &this
}

// GetAttachmentSize returns the AttachmentSize field value if set, zero value otherwise.
func (o *EmailAttachment) GetAttachmentSize() int32 {
	if o == nil || IsNil(o.AttachmentSize) {
		var ret int32
		return ret
	}
	return *o.AttachmentSize
}

// GetAttachmentSizeOk returns a tuple with the AttachmentSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailAttachment) GetAttachmentSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.AttachmentSize) {
		return nil, false
	}
	return o.AttachmentSize, true
}

// HasAttachmentSize returns a boolean if a field has been set.
func (o *EmailAttachment) HasAttachmentSize() bool {
	if o != nil && !IsNil(o.AttachmentSize) {
		return true
	}

	return false
}

// SetAttachmentSize gets a reference to the given int32 and assigns it to the AttachmentSize field.
func (o *EmailAttachment) SetAttachmentSize(v int32) {
	o.AttachmentSize = &v
}

// GetAttachmentName returns the AttachmentName field value if set, zero value otherwise.
func (o *EmailAttachment) GetAttachmentName() string {
	if o == nil || IsNil(o.AttachmentName) {
		var ret string
		return ret
	}
	return *o.AttachmentName
}

// GetAttachmentNameOk returns a tuple with the AttachmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailAttachment) GetAttachmentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentName) {
		return nil, false
	}
	return o.AttachmentName, true
}

// HasAttachmentName returns a boolean if a field has been set.
func (o *EmailAttachment) HasAttachmentName() bool {
	if o != nil && !IsNil(o.AttachmentName) {
		return true
	}

	return false
}

// SetAttachmentName gets a reference to the given string and assigns it to the AttachmentName field.
func (o *EmailAttachment) SetAttachmentName(v string) {
	o.AttachmentName = &v
}

// GetAttachmentId returns the AttachmentId field value if set, zero value otherwise.
func (o *EmailAttachment) GetAttachmentId() string {
	if o == nil || IsNil(o.AttachmentId) {
		var ret string
		return ret
	}
	return *o.AttachmentId
}

// GetAttachmentIdOk returns a tuple with the AttachmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailAttachment) GetAttachmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentId) {
		return nil, false
	}
	return o.AttachmentId, true
}

// HasAttachmentId returns a boolean if a field has been set.
func (o *EmailAttachment) HasAttachmentId() bool {
	if o != nil && !IsNil(o.AttachmentId) {
		return true
	}

	return false
}

// SetAttachmentId gets a reference to the given string and assigns it to the AttachmentId field.
func (o *EmailAttachment) SetAttachmentId(v string) {
	o.AttachmentId = &v
}

func (o EmailAttachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttachmentSize) {
		toSerialize["attachmentSize"] = o.AttachmentSize
	}
	if !IsNil(o.AttachmentName) {
		toSerialize["attachmentName"] = o.AttachmentName
	}
	if !IsNil(o.AttachmentId) {
		toSerialize["attachmentId"] = o.AttachmentId
	}
	return toSerialize, nil
}

type NullableEmailAttachment struct {
	value *EmailAttachment
	isSet bool
}

func (v NullableEmailAttachment) Get() *EmailAttachment {
	return v.value
}

func (v *NullableEmailAttachment) Set(val *EmailAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAttachment(val *EmailAttachment) *NullableEmailAttachment {
	return &NullableEmailAttachment{value: val, isSet: true}
}

func (v NullableEmailAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


